### ISSUE TITLE
Nix related text when us-nix is false

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#123]
**Description**

Having a bobfile like:

```yaml
build:
  build:
    input: ./hugo
    cmd: cd hugo && go build -o ../build/hugo  main.go
````

we get the following output:

```
➜  hugo-contrib bob build
Building nix dependencies...
Succeeded building nix dependencies
Running task build with 0 dependencies

build      	running task...
build      	...done

● ● ● ●
Ran 1 tasks in 6.95s
build              	✔       	(6.95s)
```

**Todo**
We should not have nix related text if nix is not enabled
