### ISSUE TITLE
The actual error message is not displayed for a failing task

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#169]
Run this in our example/server-db:

With a bobfile like bellow when the `server/rest-api/generated` path is not existing:

```yaml
version: 0
dependencies: [
  go_1_18,
  oapicodegen_v1.6.0.nix,
]
build:
  generate-api:
    input: openapi.yaml
    cmd: |-
      oapi-codegen -package generated -generate types -o server/rest-api/generated/types.gen.go openapi.yaml
      oapi-codegen -package generated -generate server -o server/rest-api/generated/server.gen.go openapi.yaml
    target: |-
      server/rest-api/generated/types.gen.go
      server/rest-api/generated/server.gen.go
  build:
    input: |-
      ./server
      go.mod
      go.sum
      main.go
    cmd: go build -o ./build/server main.go
    dependson:
      - generate-api
    target: ./build/server
```

running `bob build` fails with:

```shell
➜  server-db git:(main) ✗ bob build
Building nix dependencies...
Succeeded building nix dependencies
Running task build with 1 dependencies

generate-api            running task...
Shell command execute error: exit status 1

```

**Issue**: The error why generate-api is failing which is `error writing generated code to file: open server/rest-api/generated/types.gen.go: no such file or directory` is not displayed.

**Todo**: Find a solution to display the message of failing build task
