### ISSUE TITLE
bob inspect input has 

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#170]
For a Bobfile: 

```yaml
build:
  build:
    input: "*"
    cmd: echo "Hello build!"
```

running `bob inspect input build` will display the number of inputs, ex. "Task build has 3 inputs"

For 

```yaml
build:
  build:
    cmd: echo "Hello build!"
```

running `bob inspect input build` will say "Task build has 0 inputs"

However, it should say _"Task build has 3 inputs"_ because based on [our docs](https://bob.build/docs/usage/build/) _"By default the entire directory is considered (*)"_ for input.
