### ISSUE TITLE
Write a guide about targets

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#171]
Currently the[ usage of target](https://bob.build/docs/api-reference/bobfile/#target) is under bobfile reference.

We should have a proper section under Using bob about all the types of targets and how they are created/used.

Mention how a target image is created with `docker build -t imageName` and then can set `target: imageName`

Also make sure to clarify bellow(taken from a Discord message):

Another thing that is buzzing me regarding `target` node. In our docs we say:

"target - defines the output of a task. Can be a single file, entire directory or even a docker image." When I read that with fresh eyes I assumed that the value from `target` is somehow used when generating the output of the task. But for:

```yaml
build:
  generateHello:
    cmd: touch hello.txt
    target: hello.txt
```

I could also have

```yaml
build:
  generateHello:
    cmd: touch hello.txt
```

and in this second case, my task is generating the `hello.txt` file even though I don't specify the `target` node. Not sure if it's only me but I feel here there is some ambiguity here.
