### ISSUE TITLE
bobfile: task decoration

### ISSUE THREAD

**Issue by Equanox** [benchkram/bob#209]
Imaging a situation like this.

* service1 & service2 are separated in different repositories
* service1 contains an IDL document (openapi,protobuf) 
* service2 needs to call  service1 but wants to generate a client for that.

Possible solutions:
1. create a third repository and generate the client there. (Must be consumed by service2 and kept up to date)
2. create a toplevel repo containing service1 & service2 which takes control over codegen (Consider: builds from service2 must be aware that they can only start after codegeneration is complete)

Solution 2  requires us to alter a imported task which could look like this:
```yaml
# bob.yaml
import:
  - second
build:
  # Decorate an imported task 
  second/build:
    dependsOn:
      - codegeneration 
  codegeneration:
    cmd: ...
```

Details:
  * A "/" in the taskname should indicate that this is a decoration operation.. therefore the task must exists. If not `bob` should return an error.
  * Currently only "dependsOn" should be decorated. I don't see a need for "inputs, cmd or target". We basically want to change the DAG not the inner workings of a task.

Here is a branch with some predefined tests #210
