### ISSUE TITLE
`bob build` inputs not handled properly in case of relative paths

### ISSUE THREAD

**Issue by rdnt** [benchkram/bob#223]
If a file is an input of a task but it's also declared as target in a dependency of the task, then:

- It is handled correctly if the file is not prepended with `./`
- It is mistakenly added as input if the file is prepended with `./`

Examples

```yaml
input: |
    my-binary     <--- is excluded properly

input: |
    ./my-binary   <--- is added as input
```

In my tests, directories work as expected and are excluded either way.
