### ISSUE TITLE
Negative duration when dependsOn task fails

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#236]
### Steps to reproduce

Have a bob.yaml file:

```yaml
build:
  build:
    cmd: echo hello
    dependsOn:
      - another
      - yetAnother
  another:
    cmd: echo "hello
  yetAnother:
    cmd: echo "yet another"
```

Run `bob build`

Current behaviour:

```shell
Building nix dependencies...
Succeeded building nix dependencies
Running task build with 2 dependencies
Using 8 workers


● ● ● ●
Ran 2 tasks in 0.6ms
  another                       failed          (0.5ms)
  yetAnother                            (-9223372036854.7ms)

yetAnother        yet another
Shell command parse error: 1:6: reached EOF without closing quote "
````

The task `yetAnother` which was not started shows (-9223372036854.7ms)
