### ISSUE TITLE
Improve nixpkgs possible values

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#264]
Currently, to pin the nixpkgs version in the Bobfile we use:

```yaml
nixpkgs: https://github.com/NixOS/nixpkgs/archive/3590f02e7d5760e52072c1a729ee2250b5560746.tar.gz
```

Maybe we can improve on this to also specify a certain tag

Example:
```yaml
nixpkgs: nixpkgs-unstable 
nixpkgs: stable
nixpkgs: 22.0
```
