### ISSUE TITLE
Incorrect dependency caching

### ISSUE THREAD

**Issue by rdnt** [benchkram/bob#275]
Consider the following example:

```yaml

build:
  one:
    input: file1
    cmd: touch file2
    target: file2
  two:
    dependsOn:
      - one
    input: file3
    cmd: touch file4
    target: file4
```

- We run `bob build two` (both tasks are re-built)
- If we then modify `file1`, and run `bob build one`, the task is properly re-built.
- If we now run `bob build two`, it will show as `cached`, even if the target of `one` has changed.
