### ISSUE TITLE
Add a cmd option to `bob run`

### ISSUE THREAD

**Issue by puengel** [benchkram/bob#28]
For permanent run tasks e.g. in vue serve ui it would be nice to have this as a bob run task.

Example:
```yaml
runs:
    ui:
        cmd: |
            npm run serve
```
