### ISSUE TITLE
Stop and return error when target has not been created

### ISSUE THREAD

**Issue by puengel** [benchkram/bob#324]
## Scenario
The expected target is never created. You can achieve this with the following sample build command.
```yaml
build:
  container: 
    input: |
      ./Dockerfile
    cmd: |
      docker build ---tag image-name:latest . < Dockerfile
    target:
      image: some-other-name:latest
```

## Problem
Even after completion of the cmd execution bob will keep running and wait for the target to be created. Can't stop execution with ctrl+c. 

## Possible Solution
After successful cmd execution has completed bob should expect the target to exist. If the target is still missing the task should be marked as failed and a message should be displayed telling "Target for task <taskname> has not been created. This is probably not an issue with bob. Check the task logs for more details."

_Optional_: Add a delay after cmd execution to wait for the target. Could lead to additional build times..
