### ISSUE TITLE
Add option to show logs when a dependson fail

### ISSUE THREAD

**Issue by ethanquix** [benchkram/bob#355]
When a build has `dependsOn` and one of them fail, there is no log.

Example:

```
Ran 9 tasks in 87.1ms
  src/shared/proto/test                                         cached          (3.2ms)
  src/projects/lambda_logs_handler/test                         failed          (86.8ms)
```

bob.yaml
```
build:
  test:
    path: .
    dependsOn:
       -   src/shared/proto/test
       - src/projects/lambda_logs_handler/test
```

As you can see, `src/projects/lambda_logs_handler/test` failed and I have no information as why
