### ISSUE TITLE
Noop Run Tasks

### ISSUE THREAD

**Issue by rdnt** [benchkram/bob#36]
A user should be able to define a run task that does not run a command/binary or set up a compose environment. This can be useful when grouping tasks together to e.g. bring a dev environment up.

Considering the inference of task type (binary / compose) based on the path provided, as well as the ability to run shell scripts from inside run tasks, an example usecase could be the following:

```yml
run:
  compose:
    path: docker-compose.yaml
  server:
    path: ./build/server
    dependson:
      - build
      - compose
  ui:
    cmd: npm --prefix ui run serve
  dev:                                    # <--- noop task
    dependson:
      - server
      - ui
```

A noop task should not show a status tab on the TUI.
