### ISSUE TITLE
`bob run`: add option to use ui development servers

### ISSUE THREAD

**Issue by Equanox** [benchkram/bob#40]
When running a local environment with multiple frontends it is tedious to start them by hand in multiple shells. This issue is about adding support for development with hot reload capacities. 

##  Consider
* Stream `cmd` output correctly to the tui started by `bob run`. Consider how terminal reset can be handled correctly (e.g. vue's dev server cleans the output after a successful build)
* The `cmd` run task could probably implement the noop issue https://github.com/benchkram/bob/issues/36

## Example bob.yaml
```
run:
  server:
    type: binary
    path: ./build/server
    dependson:
      - build
  ui:
    cmd: npm run serve
    dir: ./ui
    dependson:
      - server
```
