### ISSUE TITLE
Incorrect value for project when inspecting an artifact 

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#94]
## Steps to reproduce

On a fresh playground with a bobfile containing:

```yaml
project: customName
```

1. Run `bob clean` to make sure all artifacts are cleared. You can validate that artifacts are cleared by running  `ls ~/.bobcache/artifacts` and checking that the directory is empty.
2. Run `bob build` to create an artifact. Get the artifact id from `ls ~/.bobcache/artifacts`. 
3. Inspect the artifact. Ex. `bob inspect artifact --id 83b9c10614d67dbf`

**Output**:

```bash
Artifact Info
  targets:
    targets/run
  metadata:
    taskname: build
    inputHash: 83b9c10614d67dbf
    project: /home/andrei/testare
    createdAt: 06 Jun 22 14:01 +0300
    targetType: path
```

**Desired Output**:

```
Artifact Info
  targets:
    targets/run
  metadata:
    taskname: build
    inputHash: 83b9c10614d67dbf
    project: customName
    createdAt: 06 Jun 22 14:01 +0300
    targetType: path
```

The project should equal `customName` not  `/home/andrei/testare`.  `/home/andrei/testare` should be set only if project is missing from bobfile.
