### ISSUE TITLE
nix: consider nix dependecies in run-tasks

### ISSUE THREAD

**Issue by Equanox** [benchkram/bob#97]
Run commands affected by `Init` & `InitOnce` should also get their dependencies from nix.

Also check if #86 need adaptions.

**Comment by zuzuleinen** [comment]
Example to test Init on server example:

```yaml
version: 0
build:
  generate-api:
    input: openapi.yaml
    cmd: |-
      oapi-codegen -package generated -generate types -o server/rest-api/generated/types.gen.go openapi.yaml
      oapi-codegen -package generated -generate server -o server/rest-api/generated/server.gen.go openapi.yaml
    target: |-
      server/rest-api/generated/types.gen.go
      server/rest-api/generated/server.gen.go
  build:
    input: |-
      ./server
      go.mod
      go.sum
      main.go
    cmd: go build -o ./build/server main.go
    dependson:
      - generate-api
    target: /build/server
run:
  server:
    type: binary
    path: ./build/server
    dependson:
      - build
      - database
    init: "php -v"
    dependencies:
      - php
  database:
    type: compose
    path: docker-compose.yml
use-nix: true
dependencies:
    - go_1_18
```
